### ISSUE TITLE
ACE 6.3.3

### ISSUE THREAD

**Issue by facontidavide** [Servicerobotics-Ulm/AceSmartSoftFramework#2]
Hi, 

I am trying to install this on Ubuntu 16.04. I am wondering the reason why you need the specific version of ACE 6.0.2. 

Will it compile if you use the version 6.3.3 that can be installed using apt-get ?

https://packages.ubuntu.com/xenial/libace-dev

Cheers

**Comment by alex-lotz** [comment]
Hi,

the ACE version 6.3.3 should work theoretically as well. However, we are very cautious with following the newer versions as we had some problems in the past when switched to newer versions. Also, we have tested the currently officially supported version 6.0.2 on different platforms like Windows, OSx and various Linux derivates. Yet, feel free to try the packaged version, however at your risk then. :-)

Cheers,
Alex

**Comment by haianos** [comment]
@facontidavide have you tried ACE 6.3.3 in the end?

**Comment by mclutz** [comment]
It is working with the Ubuntu 18.04 (6.4.5) and 20.04 (6.4.5) package from the default repos.
